version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    container_name: app-service
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - app-network
  composer_installation:
    container_name: composer_installation
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs
  nginx:
    build:
      context: ./docker/nginx
    container_name: nginx-service

    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - app

  db:
    image: 'mysql/mysql-server:8.0'
    container_name: db-service
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - dbdata:/var/lib/mysql
      - ./Dump20230606.sql:/docker-entrypoint-initdb.d/Dump20230606.sql

    networks:
      - app-network
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local